//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hospital.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class doctor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public doctor()
        {
            this.patien_doctor = new HashSet<patien_doctor>();
        }
    
        public int id { get; set; }
        public string fullName { get; set; }
        public string rating { get; set; }
        public string comment { get; set; }
        public string image { get; set; }
        public Nullable<int> idClass { get; set; }
        public Nullable<int> idHistory { get; set; }
    
        public virtual @class @class { get; set; }
        public virtual history history { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<patien_doctor> patien_doctor { get; set; }
    }
}
