//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hospital.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class patien_doctor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public patien_doctor()
        {
            this.role1 = new HashSet<role>();
        }
    
        public int role { get; set; }
        public Nullable<int> idPatient { get; set; }
        public Nullable<int> idDoctor { get; set; }
    
        public virtual doctor doctor { get; set; }
        public virtual patient patient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<role> role1 { get; set; }
    }
}
